
AWSTemplateFormatVersion: "2010-09-09"

Description: 
	This is infras as code (IaC) for the FrontEnd reactJS
	named TravelWala.
	This will be built based on nested stack structure.

Parameter:
	InfrasCodeURL: 
		Description: The URL point to the nested cloudformation code (link to that on the github repo)
		Type: String

	NetworkFormationURL:
		Description: URL for the nested network stack template
		Type: String

Mappings:
	set of mappings

Conditions:
	set of conditions

Resources:
	NetworkFormationStack:
		Type: 'AWS::CloudFormation::Stack'
		Properties:
			TemplateURL: !Ref NetworkFormationURL
			Parameters:
				ApplicationName: !Ref AWS::StackName
				VPCId: !Ref VPCId
			TimeoutInMinutes: 5



Outputs:
	set of outputs
