version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions: 
      nodejs: 12
    commands: 
      - npm install
      - echo "INSTALLED NODEMODULES" 
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "build/**/*"
    - appspec.yml
    - "scripts/*"
  discard-paths: no
